server:
  port: 8080

spring:
  application:
    name: schedule
  profiles:
    active: dev
  config:
    import: application-secret.yaml
  h2:
    console:
      enabled: false
  jooq:
    sql-dialect: POSTGRES
#    logging:
#      enabled: true
#  적용시 시큐리티가 junit 테스트 통과를 못함
#  mvc:
#    servlet:
#      path: /api


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.boot.autoconfigure.security: DEBUG
    org.jooq.tools.LoggerListener: DEBUG
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR


management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always


jwt:
  secret: ho0PCPYX5o5x0xNZhSGjkLgKMHLbsrPdX4plfRCWPf8=
  expiration:
    access: 86400000 # 하루
    refresh: 86400000 # 하루