create table IF NOT EXISTS users
(
    id         bigint generated by default as identity
        primary key,
    authority  varchar(10)
        constraint users_authority_check
            check ((authority)::text = ANY
                   ((ARRAY ['ROLE_USER'::character varying, 'ROLE_ADMIN'::character varying])::text[])),
    avatar     varchar(100),
    created_at timestamp(6) not null,
    email      varchar(100) not null
        constraint uk6dotkott2kjsp8vw4d0m25fb7
            unique,
    name       varchar(100),
    password   varchar(255),
    updated_at timestamp(6) not null
);


create table IF NOT EXISTS refresh_tokens
(
    id          bigint generated by default as identity
        primary key,
    created_at  timestamp(6) not null,
    expiry_date timestamp(6),
    token       varchar(255),
    updated_at  timestamp(6) not null,
    user_id     bigint
        constraint fk1lih5y2npsf8u5o3vhdb9y0os
            references users
);

create table IF NOT EXISTS groups
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp(6) not null,
    group_name varchar(255) not null,
    updated_at timestamp(6) not null
);

create table IF NOT EXISTS group_members
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp(6) not null,
    role       varchar(255)
        constraint group_members_role_check
            check ((role)::text = ANY ((ARRAY ['ADMIN'::character varying, 'MEMBER'::character varying])::text[])),
--             check (role in ('ADMIN', 'MEMBER'))
    updated_at timestamp(6) not null,
    group_id   bigint
        constraint fk_group_members_group
            references groups(id),
    user_id    bigint
        constraint fk_group_members_user
            references users(id),
    invite_email varchar(100),
    status varchar(10)
        check ((role)::text = ANY ((ARRAY ['PENDING'::character varying, 'JOINED'::character varying])::text[])),
    user_name varchar(100)
);

create table group_invitations
(
    id         bigint generated by default as identity
        primary key,
    group_id   bigint
        constraint fk_group_invitations_group
        references groups (id),
    user_id    bigint
        constraint fk_group_invitations_user
        references users (id),
    created_at timestamp default now(),
    update_at timestamp default now()
);

create table IF NOT EXISTS jobs
(
    id          bigint generated by default as identity
        primary key,
    created_at  timestamp(6) not null,
    description varchar(500),
    end_date    timestamp(6) not null,
    hex_color   varchar(7),
    open_type   varchar(255)
        constraint jobs_open_type_check
            check ((open_type)::text = ANY
                   ((ARRAY ['PUBLIC'::character varying, 'PRIVATE'::character varying, 'MASKED'::character varying])::text[])),
    start_date  timestamp(6) not null,
    title       varchar(255) not null,
    updated_at  timestamp(6) not null,
    user_id     bigint
        constraint fkra3g6pshf0p0hv5aisuh3weg8
            references users
);


alter table group_members
    owner to admin;

alter table groups
    owner to admin;

alter table jobs
    owner to admin;

alter table refresh_tokens
    owner to admin;

alter table users
    owner to admin;