create table IF NOT EXISTS users
(
    id         bigint generated by default as identity
        primary key,
    authority  varchar(10)
        constraint users_authority_check
--             check ((authority)::text = ANY
--                    ((ARRAY ['ROLE_USER'::character varying, 'ROLE_ADMIN'::character varying])::text[])),
            check (authority in ('ROLE_USER', 'ROLE_ADMIN')),
    avatar     varchar(100),
    email      varchar(100) not null
        constraint uk6dotkott2kjsp8vw4d0m25fb7
            unique,
    name       varchar(100),
    password   varchar(255),
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null
);


create table IF NOT EXISTS refresh_tokens
(
    id          bigint generated by default as identity
        primary key,
    expiry_date timestamp(6),
    token       varchar(255),
    user_id     bigint
        constraint fk_refresh_tokens_user
            references users(id),
    created_at  timestamp(6) not null,
    updated_at  timestamp(6) not null
);

create table IF NOT EXISTS groups
(
    id         bigint generated by default as identity
        primary key,
    group_name varchar(255) not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null
);

create table IF NOT EXISTS group_members
(
    id         bigint generated by default as identity
        primary key,
    role       varchar(255)
        constraint group_members_role_check
            check (role in ('ADMIN', 'MEMBER')),
    group_id   bigint
        constraint fk_group_members_group
            references groups(id),
    user_id    bigint
        constraint fk_group_members_user
            references users(id),
    invite_email varchar(100),
    status varchar(10)
        check (status in ('PENDING', 'JOINED')),
    user_name varchar(100),
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null
);

create table IF NOT EXISTS jobs
(
    id          bigint generated by default as identity
        primary key,
    title       varchar(255) not null,
    description varchar(500),
    hex_color   varchar(7),
    start_at  timestamp(6) not null,
    end_at    timestamp(6) not null,
    contents_policy_type   varchar(10)
        constraint jobs_contents_policy_type_check
            check (contents_policy_type in ('PUBLIC', 'PRIVATE', 'MASKED')),
    owner_type  varchar(10)
        constraint jobs_owner_type_check
            check (owner_type in ('GROUP', 'USER')),
    group_id    bigint
        constraint fk_job_group
            references groups (id)
        constraint jobs_group_id_owner_type_check
            check ((owner_type = 'USER' and group_id is null)
                or (owner_type = 'GROUP' and group_id is not null)),
    user_id     bigint
        constraint fk_job_user
            references users (id),
    created_at  timestamp(6) not null,
    updated_at  timestamp(6) not null
);


alter table group_members
    owner to admin;

alter table groups
    owner to admin;

alter table jobs
    owner to admin;

alter table refresh_tokens
    owner to admin;

alter table users
    owner to admin;